### ISSUE TITLE
curl https://install.edgee.app | sh

### ISSUE THREAD

**Issue by SachaMorard** [edgee-cloud/edgee#86]
`install.sh` script is now served by `install.edgee.app` domain. Unfortunately, there is a little bug when I try to use it to install `edgee`.<br><br>Here is what I have:

```bash
curl https://install.edgee.app | sh     
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2485  100  2485    0     0   108k      0 --:--:-- --:--:-- --:--:--  110k
                                    E D G E E
                                    Installer

--------------------------------------------------------------------------------
Website:        https://www.edgee.cloud
Documentation:  https://docs.edgee.cloud/introduction
--------------------------------------------------------------------------------

Downloading: https://github.com/edgee-cloud/edgee/releases/latest/download/edgee.aarch64-apple-darwin
curl: (23) Failure writing output to destination
```

Then, it should be cool to explain how to install `edgee` with this simple command line in the readme, and in the documentation.

**Comment by KokaKiwi** [comment]
I would need more information to get a precise view of the bug:
- Where did you run the command?
- Which curl version do you use and how was it installed?

Also could you re-run the command using `curl https://install.edgee.app/ | bash -x`? (in order to get more debug infos about the commands run by the script)
